### ISSUE TITLE
Lightbulb "exclude rule"

### ISSUE THREAD

**Issue by bardware** [KamasamaK/vscode-cflint#10]
Hi,

I highlighted some code (double clicked a word) and to my surprise a lightbulb appeared.
Please tell me what will happen when I click `Exclude rule in .cflint`. Will it disable the check for that rule?

![grafik](https://user-images.githubusercontent.com/802702/47442710-18cce880-d7b3-11e8-904b-64cd46fda606.png)

Thanks for keeping this plugin up to date.

**Comment by KamasamaK** [comment]
That light bulb indicates that there are quick fixes/code actions available for the current selection. It is also displayed next to a selected problem in the Problems view. The "exclude rule" option listed there will add that rule to `excludes` within the `.cflint` for you. Other available code actions are listed in the [README](https://github.com/KamasamaK/vscode-cflint#code-actions) and are very limited based on the rule.

**Comment by bardware** [comment]
Missed that README; thank you!
