### ISSUE TITLE
Does cflint in SCM compare view respect .cflintrc?

### ISSUE THREAD

**Issue by bardware** [KamasamaK/vscode-cflint#11]
Hi,

I look at the files I modified, click on one and the the local version and the previous version of that file appera in a split view. In Windows Taskmanager I see the linter runs on both files. (Two JAVA processes) I have a `.cflintrc` file in my project root. As far as I understand Code copies the file versions to a `tmp` folder. Is cflint run there? Is the `.cflintrc` considered, that is supposed to limit the number of tests, or does it run a full scan?

Best,
Bernhard

**Comment by KamasamaK** [comment]
The extension will run CFLint for any document that is identified as `cfml` language and `file` or `untitled` scheme. If it is copying into a `tmp` folder then CFLint will not find the `.cflintrc` file. You should be able to use the `cflint.altConfigFile` settings to apply a rule config in that case.

**Comment by bardware** [comment]
Seems to do the trick; thanks alot!
