### ISSUE TITLE
Creating empty ordered struct

### ISSUE THREAD

**Issue by shaedrich** [KamasamaK/vscode-cflint#13]
Hey KamasamaK,

if I create an empty ordered struct, your linter shows a message, that `newStruct()` shouldn't be used. Instead I should use `{}` but I don't think `newStruct('ordered')` has such an equivalent, does it?

Best regards

**Comment by KamasamaK** [comment]
See cflint/CFLint#607 for the upstream issue. This is just an extension that integrates the linter into VS Code, so issues with the linter itself should go there.

**Comment by shaedrich** [comment]
Sorry.
