### ISSUE TITLE
Root .cflintrc configuration being ignored

### ISSUE THREAD

**Issue by homestar9** [KamasamaK/vscode-cflint#14]
I've run into an issue where it appears as if the root .cflintrc file is being ignored by the VS code plugin.

I am currently using: CFLint-1.4.1-all.jar
My .cflintrc file looks like this: https://pastebin.com/d7GXVgLR and is located in the project root.

For example, I configured the   "FUNCTION_TYPE_MISSING" to be ignored, yet I still get the following in the editor:

![image](https://user-images.githubusercontent.com/5341142/54885017-aa10bb80-4e34-11e9-815b-7e4e055fb0b9.png)

I opened the VS Code console and only see the following:
```
[Extension Host] [2019-03-24 12:56:23] C:\ProgramData\Oracle\Java\javapath\java.exe -jar D:\Dropbox\Settings\CFLint\CFLint-1.4.1-all.jar -stdin d:\Repositories\test-repo\models\agent\AgentForm.cfc -q -e -json -stdout
```

**Comment by KamasamaK** [comment]
This is generally the responsibility of CFLint, and I believe this is working in v1.4.1 (the latest stable version). You may open a [CFLint issue](https://github.com/cflint/CFLint/issues) if you've found that it's not detecting your `.cflintrc`. In the meantime, you may try using the `cflint.altConfigFile` setting for this extension.

**Comment by homestar9** [comment]
Thank you. I have created [an issue at the CFLint repo](https://github.com/cflint/CFLint/issues/624).

Setting the `cflint.altConfigFile` works for the time being.  Hopefully I'll be able to figure out a solution so I don't have to manually specify the config file.

Debug output with altConfigFile specified:
```
[Extension Host] [2019-04-19 13:36:10] C:\ProgramData\Oracle\Java\javapath\java.exe -jar D:\Dropbox\Settings\CFLint\CFLint-1.4.1-all.jar -stdin d:\Repositories\test-repo\models\agent\AgentForm.cfc -q -e -json -stdout -configfile d:\Repositories\test-repo\.cflintrc
```
