### ISSUE TITLE
cflint.exclude does not seem to work

### ISSUE THREAD

**Issue by joshuacurtiss** [KamasamaK/vscode-cflint#15]
Hello, thank you very much for your extension.  I am try to use `cflint.exclude` in my project settings to exclude the `builds` directory from being processed by cflint extension, and no matter what I do, cflint processes the files when I build my project into the `builds` directory.

```
{
    "cflint.exclude": ["builds/*"]
}
```

I have tried these variations and none seem to work: 
  * `"builds"`
  * `"builds/*"`
  * `"builds/*/*"`
  * `"builds/**/*"`
  * `"builds/**/*.*"`
  * `"/builds/**.cf*"`
  * `"/builds/**/*"`

Incidentally the project is being built with Gulp.  When the files are built, cflint starts processing all of them immediately.

Your help/ideas are appreciated.

VS Code version: 1.34.0 (Mac)
Extension version: 0.3.3
CFLint version: 1.4.1

**Comment by KamasamaK** [comment]
I have looked into this and found that the pattern is being compared to the absolute physical path of the file instead of the relative path. I've seen this done both ways, but I think the relative path makes more sense so I will update the code to use relative path instead.

**Comment by joshuacurtiss** [comment]
I didn't even think to check an absolute system path. That works great, thank you, I can now keep cflint from blowing up when I do my builds! 😄  Adjusting to use relative path will be useful to me as I use VS Code's workspace settings so my team can pull in settings for linting, formatting, etc as part of the source control. Thanks.

**Comment by joshuacurtiss** [comment]
Or, I've come to appreciate that this works as well:
```
"cflint.exclude": [
    "**/builds/**/*"
]
```

**Comment by KamasamaK** [comment]
The new extension version (0.3.4) changes that pattern matcher to compare against the file's path relative to the workspace root/folder.

**Comment by joshuacurtiss** [comment]
Excellent and many thanks!

**Comment by dbelanger** [comment]
Hey @KamasamaK, I seem to be having this same issue now as well.  I'm running:

- VS Code version: 1.66.2 (PC)
- Extension version: 0.3.6
- CFLint version: 1.5.0

Basically what's happening is exactly what Josh said except that for me it's when I do an initial "install" of any CB project, the linter is running on every cfc in **coldbox**, **testbox** and **modules** directories.  I have a **.cflintrc** file in the directory in question (there's no "exclude" key) and I've tried adding the following excludes in the settings.json of VSCode without success.  
`"cflint.exclude": [
"**/modules/**.cfc",
"**/coldbox/**.cfc",
"**/testbox/**.cfc"
],`
No matter what I do, every single cfc still gets scanned on install... I've even tried variations of that like `modules/**.cfc` or `/modules/**.cfc` to no avail.

Additionally, I tried pasting the above directly into the .cflintrc but still no luck...

**Comment by KamasamaK** [comment]
@dbelanger I believe `**` only matches directories, so you would need to use for example `"**/modules/**/*.cfc"` instead to exclude CFCs. Or if you want it to exclude all of the files, use `"**/modules/**"`.

**Comment by dbelanger** [comment]
Yup, that did it!  Sorry about that, I was following the example at https://commandbox.ortusbooks.com/usage/parameters/globbing-patterns
