### ISSUE TITLE
Extension Host Error "Cannot Read Property 'getAPI'

### ISSUE THREAD

**Issue by homestar9** [KamasamaK/vscode-cflint#17]
It looks like CFLint stopped working for me in the latest VS Code 1.37.1

When I open a CFM page, I see the following in the dev console:

`[Extension Host] [2019-09-05 12:15:36] cflint is active!
console.ts:137 [Extension Host] TypeError: Cannot read property 'getAPI' of undefined	at activate (C:\Users\Henweigh\.vscode\extensions\kamasamak.vscode-cflint-0.3.4\out\src\extension.js:695:43)	at Function._callActivateOptional (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:764:518)	at Function._callActivate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:764:207)	at define._doActivateExtension.Promise.all.then.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:763:245)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:572
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:572
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94`
Screenshot attached:
![image](https://user-images.githubusercontent.com/5341142/64373949-9ff40b00-cfd7-11e9-8710-9efdbc238486.png)

**Comment by KamasamaK** [comment]
That is an expected error right now and the extension can function fine without it.

I was able to use the extension fine with VS Code 1.37.1 and currently with 1.38.0, so I am unable to determine the issue with the current information.

**Comment by homestar9** [comment]
Okay, good to know.  I'll close the ticket and do a little more digging.  Thanks for the response! :)
