### ISSUE TITLE
VSCode v1.38 - lint result not shown in popup

### ISSUE THREAD

**Issue by bardware** [KamasamaK/vscode-cflint#18]
Hi,

after the recent update to VSCode v1.38 the popups, that appear when I hover over an ColdFusion tag with the mouse, look differently. I'm pretty sure before they contained the CFLint result and an explanation of the CF keyword. Now, the CFLint result is missing and the explanations displays a placeholder for images.

![grafik](https://user-images.githubusercontent.com/802702/64593102-bb7f5d00-d3ad-11e9-9004-7bb50a258b12.png)

**Comment by KamasamaK** [comment]
The diagnostic showing in hover is something that comes free with a diagnostic and not something controlled directly. In my testing, it is still there, but at the bottom. I thought they used to be at the top. I think microsoft/vscode#73120 covers this issue.

The explanation of the keyword is unrelated to this extension. The placeholder images issue you're seeing from that is resolved for VS Code v1.38.1.

**Comment by bardware** [comment]
Just received the VSCode Update - Popup looks good again.

Thnak you!

![grafik](https://user-images.githubusercontent.com/802702/64772246-9119d500-d550-11e9-90e7-443b61db4f4a.png)
