### ISSUE TITLE
Export CFLINT results

### ISSUE THREAD

**Issue by antoz87** [KamasamaK/vscode-cflint#4]
Is there a way to export the results in some kind of file (like HTML when you run CFLINT from command line? also txt is ok)

**Comment by KamasamaK** [comment]
If you are asking about the command line, you want the [original CFLint repo](https://github.com/cflint/CFLint). This is just an extension that integrates CFLint into VS Code.

CFLint supports exporting as HTML (default), text, XML, and JSON. See [Creating Reports](https://github.com/cflint/CFLint#creating-reports) and [How Do I Use This Tool](https://github.com/cflint/CFLint/wiki/How-Do-I-Use-This-Tool%3F) for more info on how to do this through the command line.

**Comment by antoz87** [comment]
I know I can generate the export via command line, I was only asking if there is some way to generate a report from VSCode.
Anyway thanks for the reply.

**Comment by KamasamaK** [comment]
OK. I guess it's just a matter of convenience in that case. I will consider adding exports as VS Code commands if that is something you'd find useful.

**Comment by antoz87** [comment]
It's useful for me because I have to attach the export of CFLINT into our ticketing system. Thanks again for the answer

**Comment by KamasamaK** [comment]
I have added a command for each output format and a setting for the output directory. You may bind any of these commands to a keyboard shortcut if you'd like. Please let me know if this works as you'd expect.

**Comment by antoz87** [comment]
It works very well and exactly as I need. Thank you very much.
