### ISSUE TITLE
invalid cflint.jarPath fails silently

### ISSUE THREAD

**Issue by zspitzer** [KamasamaK/vscode-cflint#8]
I had the wrong cflint.jarPath set and while the extension complains if there isn't a cflint.jarPath set, it doesn't appear to validate that the jar configured in cflint.jarPath exists

**Comment by KamasamaK** [comment]
Prior to every lint, the extension does validate if the value of `cflint.jarPath` refers to a [file that exists](https://github.com/KamasamaK/vscode-cflint/blob/0af24b1beebbe01c807527deaa788b3c4c7990e5/src/extension.ts#L325). If it does not, an error message is displayed.
