### ISSUE TITLE
Linter is stopped even though it was enabled

### ISSUE THREAD

**Issue by HadiAkmal** [KamasamaK/vscode-cflint#9]
My linter is stopped even though I already enabled it.

![image](https://user-images.githubusercontent.com/14165645/47235345-56c0ba00-d40b-11e8-975c-dff7f7f8dfe4.png)

Here is my jar path:
![image](https://user-images.githubusercontent.com/14165645/47235476-bb7c1480-d40b-11e8-9fe7-79048517db41.png)

Recently enabled linter:
![image](https://user-images.githubusercontent.com/14165645/47235575-0b5adb80-d40c-11e8-9a52-df5b50c4beca.png)

Any advice? Thanks in advance.

**Comment by KamasamaK** [comment]
Stopped does not have to do with it being enabled. That is just an indication that it is not currently running. You are pointing it to the wrong JAR file, though. Read my instructions under [Requirements](https://github.com/KamasamaK/vscode-cflint#requirements). If you are trying to build it yourself, you will find the _CFLint-*-all.jar_ in `/build/libs/`.

**Comment by HadiAkmal** [comment]
> Stopped does not have to do with it being enabled. That is just an indication that it is not currently running. You are pointing it to the wrong JAR file, though. Read my instructions under [Requirements](https://github.com/KamasamaK/vscode-cflint#requirements). If you are trying to build it yourself, you will find the _CFLint-*-all.jar_ in `/build/libs/`.

I already added the correct path but it still stopped? What did I missed?

`C:\Users\hadiakmal\Documents\work\CFLint\build\libs\CFLint-1.4.1-all.jar`

**Comment by KamasamaK** [comment]
It is "stopped" because it only runs when certain events occur e.g. saving a file or opening a new file. Do not concern yourself with the status. If it is not working or you are getting an error, then post that. If it does not work and it is not apparent why, check the console (`Ctrl`+`Shift`+`I`) and post any messages that appear to be originating from this extension.
